### ISSUE TITLE
XStraightPointer not working inside portals

### ISSUE THREAD

**Issue by Ledzz** [coconut-xr/xinteraction#2]
If I try to attach XStraightPointer to something that is inside fiber's createPortal, it doesn't work.
I've figured this is because scene is overriden in portal and xinteraction [ends up using wrong scene](https://github.com/coconut-xr/xinteraction/blob/main/src/react/straight-pointer.tsx#L96). Solved it temporarily by providing the original scene:

```tsx
function Provide() {
  const uniqueId = useMemo(() => id++, []);

  const scene = useThree((s) => s.previousRoot?.((q) => q.scene));

  const inject = useCallback(
    (prevState: RootState) => {
      const intersect: Partial<RootState> = { ...prevState }; // all prev state props

      return {
        ...intersect,
        scene,
      } as RootState;
    },
    [scene]
  );

  const previousRoot = useStore();

  const [usePortalStore] = useState(() => {
    // Create a mirrored store, based on the previous root with a few overrides ...
    const previousState = previousRoot.getState();
    const store = create<RootState>((set, get) => ({
      ...previousState,
    }));
    return store;
  });

  useEffect(() => {
    // Subscribe to previous root-state and copy changes over to the mirrored portal-state
    const unsub = previousRoot.subscribe((prev) =>
      usePortalStore.setState(() => inject(prev))
    );
    return () => {
      unsub();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inject]);

  useEffect(() => {
    usePortalStore.setState(() => inject(previousRoot.getState()));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [inject]);

  useEffect(() => {
    return () => {
      usePortalStore.destroy();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const pointerRef = useRef<InputDeviceFunctions>();

  return (
    <context.Provider value={usePortalStore}>
      <XStraightPointer id={uniqueId} direction={negZAxis} ref={pointerRef} />
    </context.Provider>
  );
}
```

**Comment by bbohlender** [comment]
Isn't that exactly what should happen? You have a portal to another scene and the pointers inside this portal to another scene only work with that scene. Curious to learn more about the use case, so I can better understand how common this is and how I can support/enable that in the furture :)

**Comment by Ledzz** [comment]
the usecase is simple - I'm trying to make react-xr and uikit work together, and I'm just attaching XStraightPointer to a react-xr's [ray](https://github.com/pmndrs/react-xr/blob/master/src/Controllers.tsx#L49). So the XStraightPointer is inside the xrController.controller, but it need to interact with objects outside the controller.

**Comment by bbohlender** [comment]
Okay, seems like a use case that is obsolete after rewriting and merging with react-xr.
Out of curiosity, why don't you use natuerlich? Are you missing some features that are present in react-xr?

**Comment by Ledzz** [comment]
> rewriting and merging with react-xr
that's what I'm waiting for 🙂

> Out of curiosity, why don't you use natuerlich? Are you missing some features that are present in react-xr?
I already have a pretty big codebase, and migrating to a other library seemed too painful and risky.
